# Generated by Django 4.0.3 on 2022-04-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=75)),
                ('nombre', models.CharField(max_length=75)),
                ('edad', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=75)),
                ('direccion', models.CharField(max_length=75)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=75)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_veterinaria.animal')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
                ('catidad', models.IntegerField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_veterinaria.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('apellidos', models.CharField(max_length=55)),
                ('fecha_contratacion', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_factura', models.CharField(max_length=75)),
                ('elemento_factura', models.ManyToManyField(to='api_veterinaria.elementofactura')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_veterinaria.personal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_veterinaria.cliente'),
        ),
    ]
